### ISSUE TITLE
Criar um contador de vendas

### ISSUE THREAD

**Issue by LuanRoger** [LuanRoger/MegabyteStore#30]
## Motivação
O relatório gerado pelo administrador precisa conter a quantidade de produtos vendidos e o dinheiro arrecadado.

## TODOs
- [x] Criar uma classe para armazenar as informações:
  - [x] Quantidade de produtos vendidos.
  - [x] Renda com a venda dos produtos.
- [x] Serializar em no arquivo .json.
- [ ] ~~Carregar o arquivo só se o usuário entrar como administrador.~~

**Comment by LuanRoger** [comment]
- Feito em #32 
Esta ultima tarefa não deve ser implementada já que o usuário também modifica as vendas quando compra algo, assim, elas devem ser carregadas também.
